version: "3.7"

services:
  dash-doodler:
    build:
      context: .
    image: dash-doodler:1.0.0
    container_name: dash-doodler
    ports:
      - "8050:8050"
    environment:
      - TARGET=LIVE
    restart: unless-stopped
